#!/bin/python

"""
Reference: https://github.com/ytdl-org/youtube-dl/blob/master/youtube_dl/__init__.py
"""

from youtube_dl import YoutubeDL
import sys
import os
import json
from argparse import ArgumentParser

url = sys.argv[1]
savefile = "/home/ozz/youtubedownloads.txt"


def parse_args():
    parser = ArgumentParser(
        description='Hosts temporary service to upload files.')
    parser.add_argument('-r',
                        '--resolution',
                        dest='res',
                        default='720p',
                        help='Resolution of image, default=720p')

    parser.add_argument('-d',
                        '--dir',
                        dest='dir',
                        default=os.getcwd(),
                        help='Stores files in specified directory. Uses local directory by default')

    parser.add_argument('-s',
                        '--save',
                        action='store_true',
                        dest='save',
                        default=False,
                        help='Save config to download later')

    parser.add_argument('-c',
                        '--continue',
                        action='store_true',
                        dest='resume',
                        default=False,
                        help='Continue saved downloads')
    parser.add_argument('url',
                        default=False,
                        help='URL')

    args = parser.parse_args()
    return args


def get_conf(url, dirc, res):
    ydl_opts = {
        'outtmpl': os.path.join(dirc, '%(title)s.%(ext)s'),
        'postprocessors': [{
            'key': 'FFmpegVideoConvertor',
            'preferedformat': 'mp4',
        }],
        'quiet': True
    }
    with YoutubeDL({'quiet': True}) as recon:
        ie = recon.get_info_extractor('Youtube')
        meta = ie.extract(url)
        formats = meta['formats']

        pref_format = False
        for fmt in formats:
            if fmt['format_note'] == res:
                pref_format = fmt['format_id']
        if pref_format:
            ydl_opts['format'] = pref_format
        else:
            print("Failed to find {0}".format(res))
        return {
            'url': url,
            'title': meta['title'],
            'conf': ydl_opts,
            'done': False
        }


def download(conf):
    print("Downloading - {0}".format(conf['title']))
    try:
        dirc = os.path.dirname(conf['conf']['outtmpl'])
        if not os.path.exists(dirc):
            print("Missing {0}".format(dirc))
            return False
        with YoutubeDL(conf['conf']) as ydl:
            ydl.download([conf['url']])
        return True
    except Exception as e:
        print(e)
        return False


def clean_up():
    with open(savefile) as f:
        items = json.load(f)
    ni = []
    for el in items:
        if not el['done']:
            ni.append(el)
    with open(savefile, 'w') as w:
        json.dump(ni, w)


if __name__ == "__main__":
    args = parse_args()

    if args.resume:
        if not os.path.exists(savefile):
            print("Done")
        else:
            with open(savefile) as f:
                items = json.load(f)
            for el in items:
                if not el['done']:
                    status = download(el)
                    if status:
                        el['done'] = True
            with open(savefile, 'w') as w:
                json.dump(items, w)
        sys.exit()
    elif args.save:
        conf = get_conf(args.url, args.dir, args.res)
        if os.path.exists(savefile):
            with open(savefile) as f:
                items = json.load(f)
        else:
            items = []
        items.append(conf)
        with open(savefile, 'w') as w:
            json.dump(items, w)
        sys.exit()

    else:
        conf = get_conf(args.url, args.dir, args.res)
        download(conf)
        print("Done")

    clean_up()
